<?php

/**
 * @file
 * Contains drupalcamp_2018.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function drupalcamp_2018_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupalcamp_2018 module.
    case 'help.page.drupalcamp_2018':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example code for Drupalcamp ATL 2018') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupalcamp_2018_theme() {
  return [
    'drupalcamp_2018' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function drupalcamp_2018_node_insert(NodeInterface $node) {
  if ($node->bundle() === 'musician') {
    \Drupal::service('plugin.manager.musician')->clearCachedDefinitions();
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function drupalcamp_2018_node_update(NodeInterface $node) {
  drupalcamp_2018_node_insert($node);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function drupalcamp_2018_node_delete(NodeInterface $node) {
  drupalcamp_2018_node_insert($node);
}
