<?php

/**
 * @file
 * Contains drupalcamp_2018.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupalcamp_2018_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupalcamp_2018 module.
    case 'help.page.drupalcamp_2018':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example code for Drupalcamp ATL 2018') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupalcamp_2018_theme() {
  return [
    'drupalcamp_2018' => [
      'render element' => 'children',
    ],
  ];
}
